### ISSUE TITLE
Regarding the license of the software

### ISSUE THREAD

**Issue by HiroIshida** [mourga/variational-lstm#3]
@mourga  Thank you for sharing your code! 
I am developing software depending on your software `variational-lstm` now. I am considering make it public in the future, where probably I will encounter a license issue as there is no license notice in your code. So, it would be so helpful if you add a license to this software.

**Comment by mourga** [comment]
Hi @HiroIshida, thank you for using my code! I just added it!

**Comment by HiroIshida** [comment]
Thank you very much!
